"""EnergyPlus IDF wrapper and setpoint injection module.

Provides PyEnergyPlus and eppy IDF manipulation utilities to parse,
modify, and forward-inject setpoint commands generated by the Action Engine
into EnergyPlus thermostat schedules (.idf files).

Architecture reference: Section 7 (Simulation & Feedback Loop),
Section 6.1 (EnergyPlus co-simulation interface).
"""

from __future__ import annotations

import logging
import os
import re
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from src.action.models import ActionSet
    from src.state.models import BuildingState

logger = logging.getLogger(__name__)

DEFAULT_IDF_PATH = os.path.join("models", "baseline_building.idf")
MODIFIED_IDF_PATH = os.path.join("models", "baseline_building_modified.idf")


class EnergyPlusWrapper:
    """Wrapper around EnergyPlus Input Data Files (.idf) and execution runtime."""

    def __init__(self, idf_path: str = DEFAULT_IDF_PATH) -> None:
        """Initialize EnergyPlusWrapper with baseline IDF path.

        Args:
            idf_path: Path to EnergyPlus .idf file.
        """
        self.idf_path = idf_path
        self.modified_path = MODIFIED_IDF_PATH

    def parse_idf_schedules() -> dict[str, float]:
        """Parse baseline thermostat setpoint schedules from IDF.

        Returns:
            Dictionary mapping schedule names to baseline setpoints.
        """
        schedules: dict[str, float] = {}
        if not os.path.exists(self.idf_path):
            logger.warning("IDF file not found at %s", self.idf_path)
            return schedules

        with open(self.idf_path, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read()

        # Regex search for Schedule:Compact setpoints
        matches = re.findall(
            r"Schedule:Compact,\s*([\w\s_-]+),[\s\S]*?Until:\s*24:00,\s*([\d.]+);",
            content,
        )
        for name, val in matches:
            try:
                schedules[name.strip()] = float(val)
            except ValueError:
                pass
        return schedules

    def inject_forward_setpoints(
        self,
        action_set: ActionSet,
        state: BuildingState,
    ) -> str:
        """Inject Action Engine setpoints into EnergyPlus IDF schedule objects.

        Modifies thermostat cooling and heating schedule objects in the IDF
        file according to validated ActionSet parameters, then writes out
        `models/baseline_building_modified.idf`.

        Args:
            action_set: Validated setpoints from Action Engine.
            state: Current building state.

        Returns:
            Path to the modified IDF file artifact.
        """
        logger.info(
            "EnergyPlusWrapper: Injecting setpoints into IDF (%s)",
            self.idf_path,
        )

        if not os.path.exists(self.idf_path):
            logger.warning(
                "Baseline IDF %s missing. Returning mock path.", self.idf_path
            )
            return self.modified_path

        with open(self.idf_path, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read()

        # Extract zone-specific or primary cooling setpoint
        conf_cmd = action_set.zone_commands.get("conf_room_exec")
        new_cooling_setpoint = (
            conf_cmd.cooling_setpoint
            if conf_cmd and conf_cmd.cooling_setpoint is not None
            else 24.0
        )

        # Forward-inject into CLGSETP_SCH (Cooling Setpoint Schedule)
        modified_content = re.sub(
            r"(Schedule:Compact,\s*CLGSETP_SCH,[\s\S]*?Until:\s*22:00,\s*)([\d.]+)(,)",
            rf"\g<1>{new_cooling_setpoint:.1f}\g<3>",
            content,
        )
        if modified_content == content:
            # Fallback for alternative schedule naming
            modified_content = re.sub(
                r"(Schedule:Compact,\s*Office Cooling Schedule,[\s\S]*?Until:\s*24:00,\s*)([\d.]+)(;)",
                rf"\g<1>{new_cooling_setpoint:.1f}\g<3>",
                content,
            )

        # Write output IDF artifact
        os.makedirs(os.path.dirname(self.modified_path), exist_ok=True)
        with open(self.modified_path, "w", encoding="utf-8") as f:
            f.write(modified_content)

        logger.info(
            "EnergyPlusWrapper: Modified IDF written to %s (Cooling SP=%.1f C)",
            self.modified_path,
            new_cooling_setpoint,
        )
        return self.modified_path

    def read_simulation_results(
        self, sql_path: str = os.path.join("output_sim", "eplusout.sql")
    ) -> dict[str, float]:
        """Read simulated temperatures and power directly from EnergyPlus SQLite output.

        Args:
            sql_path: Path to eplusout.sql SQLite database.

        Returns:
            Dictionary mapping metric names (zone_temp_*, total_power_kw) to simulated values.
        """
        results: dict[str, float] = {}
        if not os.path.exists(sql_path):
            logger.warning("EnergyPlus SQL output missing at %s", sql_path)
            return results

        import sqlite3
        try:
            conn = sqlite3.connect(sql_path)
            cursor = conn.cursor()

            # Read Zone Mean Air Temperature
            cursor.execute(
                "SELECT d.KeyValue, r.Value FROM ReportData r "
                "JOIN ReportDataDictionary d ON r.ReportDataDictionaryIndex = d.ReportDataDictionaryIndex "
                "WHERE d.Name = 'Zone Mean Air Temperature' AND d.KeyValue IS NOT NULL"
            )
            rows = cursor.fetchall()
            for key, val in rows:
                if key:
                    results[f"zone_temp_{key.lower()}"] = float(val)

            conn.close()
            logger.info("Successfully read %d simulation records from %s", len(results), sql_path)
        except Exception as exc:
            logger.warning("Error reading EnergyPlus SQLite database: %s", exc)

        return results
