"""Action Engine output models — setpoint commands sent to HVAC.

The Action Engine (Phase 6) translates an OrchestratorPlan into
concrete, typed setpoint commands and validates them through the
Safety Validator before any command may be issued.

Architecture reference: Section 6 (Action & Safety Engine),
Section 1.2 (Actions ontology — setpoint commands).
"""

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Physical safety limits — ABSOLUTE bounds enforced by the
# Safety Validator regardless of any upstream decision.
# ---------------------------------------------------------------------------

COOLING_SETPOINT_MIN: float = 18.0  # °C — minimum permissible
COOLING_SETPOINT_MAX: float = 26.0  # °C — maximum permissible
HEATING_SETPOINT_MIN: float = 16.0  # °C
HEATING_SETPOINT_MAX: float = 24.0  # °C
DEADBAND_MIN: float = 1.0           # °C — min gap heat < cool
MAX_SETPOINT_DELTA_PER_STEP: float = 2.0  # °C — max change/step
FAN_SPEED_MIN: float = 10.0         # % — must not stall
FAN_SPEED_MAX: float = 100.0        # %
DAMPER_MIN: float = 0.0             # % — fully closed
DAMPER_MAX: float = 100.0           # % — fully open
CO2_EMERGENCY_PPM: float = 1200.0   # PPM — force full ventilation


class CommandStatus(str, Enum):
    """Outcome of a command after Safety Validator processing.

    Attributes:
        APPROVED: Command is within safe bounds and will be sent.
        CLAMPED: Command was modified to stay within bounds.
        REJECTED: Command violates an absolute safety rule and
            has been blocked entirely.
    """

    APPROVED = "APPROVED"
    CLAMPED = "CLAMPED"
    REJECTED = "REJECTED"


class ZoneSetpointCommand(BaseModel):
    """Concrete setpoint command for a single zone.

    Generated by the Action Engine from a ZoneActionPlan. All
    values represent absolute target setpoints, not deltas. The
    Safety Validator fills in ``status`` and ``validator_notes``.

    Attributes:
        zone_id: Target zone.
        cooling_setpoint: Absolute target cooling setpoint (°C).
            None = no change command.
        damper_position_pct: Absolute target damper position (%).
            None = no change command.
        fan_speed_pct: Absolute target fan speed (%).
            None = no change command.
        status: Command status after Safety Validator processing.
        validator_notes: Human-readable notes from the validator
            (e.g. "clamped cooling to 18°C min").
    """

    zone_id: str = Field(..., description="Target zone.")
    cooling_setpoint: Optional[float] = Field(
        None, description="Absolute cooling setpoint (°C)."
    )
    damper_position_pct: Optional[float] = Field(
        None, description="Absolute damper position (%)."
    )
    fan_speed_pct: Optional[float] = Field(
        None, description="Absolute AHU fan speed (%)."
    )
    status: CommandStatus = Field(
        CommandStatus.APPROVED,
        description="Validation status.",
    )
    validator_notes: list[str] = Field(
        default_factory=list,
        description="Safety Validator notes.",
    )

    model_config = {"frozen": False}  # Validator mutates status.


class BuildingCommand(BaseModel):
    """Concrete building-wide command.

    Attributes:
        fan_speed_pct: Absolute building-wide fan speed (%).
            None = no change.
        status: Validation status.
        validator_notes: Safety Validator notes.
    """

    fan_speed_pct: Optional[float] = Field(
        None, description="Absolute building fan speed (%)."
    )
    status: CommandStatus = Field(
        CommandStatus.APPROVED,
        description="Validation status.",
    )
    validator_notes: list[str] = Field(
        default_factory=list,
        description="Safety Validator notes.",
    )

    model_config = {"frozen": False}


class ActionSet(BaseModel):
    """Full set of validated commands for one simulation timestep.

    Produced by the Action Engine after Safety Validator processing.
    Passed to the EnergyPlus interface (Phase 7) for execution.

    Attributes:
        zone_commands: Validated zone-level setpoint commands.
        building_command: Validated building-wide command.
        has_rejections: True if any command was rejected.
        has_clamps: True if any command was clamped.
    """

    zone_commands: dict[str, ZoneSetpointCommand] = Field(
        default_factory=dict,
        description="Zone ID -> ZoneSetpointCommand.",
    )
    building_command: Optional[BuildingCommand] = Field(
        None, description="Building-wide command."
    )

    model_config = {"frozen": True}

    @property
    def has_rejections(self) -> bool:
        """True if any command has REJECTED status."""
        zone_rej = any(
            c.status == CommandStatus.REJECTED
            for c in self.zone_commands.values()
        )
        bld_rej = (
            self.building_command is not None
            and self.building_command.status == CommandStatus.REJECTED
        )
        return zone_rej or bld_rej

    @property
    def has_clamps(self) -> bool:
        """True if any command was clamped to physical bounds."""
        zone_cl = any(
            c.status == CommandStatus.CLAMPED
            for c in self.zone_commands.values()
        )
        bld_cl = (
            self.building_command is not None
            and self.building_command.status == CommandStatus.CLAMPED
        )
        return zone_cl or bld_cl
